---
name: flir
channels:
  - conda-forge
  - nodefaults

dependencies:
  - conda-lock
  - ipykernel
  - jupyterlab
  - pandas
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - python=3.9.16
  - pyyaml
  - seaborn
  - setuptools_scm
  - scikit-fda
  - statsmodels
  - toml
  - pip:
      - -e .
      - kaleido
